### PR TITLE
Updated versions for latest react native

### PR DESCRIPTION
**Pull request by sunnymopada**

### CODE REVIEW

**Comment by sunnymopada** [comment]
@tonyxiao @sesm updated peer version

**Comment by sesm** [comment]
@SanyasiraoM Looks good!

**Comment by sesm** [comment]
@tonyxiao could you please release a version with this fix to npm? Thanks in advance!

**Comment by tonyxiao** [comment]
Done @sesm https://www.npmjs.com/package/react-native-analytics

**Pull request merged**
