### PR TITLE
Updated import statements for latest react native

### PR DESCRIPTION
**Pull request by sunnymopada**

### CODE REVIEW

**Comment by sunnymopada** [comment]
@tonyxiao @sesm updated in single PR

**Comment by sesm** [comment]
@SanyasiraoM Thank you for quick response! 
The only thing left: react-native peer dependency should be `>=0.40.0` rather then just `0.40.0`, to allow all later version.

**Comment by sunnymopada** [comment]
Will update react native version. I'm not sure how to do a same pull request

**Comment by tonyxiao** [comment]
Thanks - done here https://github.com/tonyxiao/react-native-analytics/pull/14

**Pull request closed without merging**
